### ISSUE TITLE
[Feature request] Include the DiscoverGateway() from Taipei-Torrent in this package

### ISSUE THREAD

**Issue by chmduquesne** [jackpal/go-nat-pmp#1]
The file [torrent/gateway.go](https://github.com/jackpal/Taipei-Torrent/blob/master/torrent/gateway.go) has a neat DiscoverGateway() function that could be included in this package.

I understand that this function may not always work, but could not it be included in this package?

It could be made such that if you provide `natpmp.NewClient` with the argument `nil`, it would try to guess. Does it make sense?

**Comment by zorun** [comment]
+1, it would avoid every user of the lib doing its own hacking (for instance taking the first IP address of the range, see https://github.com/fd/go-nat/blob/master/natpmp.go#L37)

**Comment by chmduquesne** [comment]
Note: If you don have time, I volonteer to implement this feature and make a pull request. You just have to tell me if you would be open to integrate that.

**Comment by jackpal** [comment]
Why don't we split the torrent/gateway.go code into its own library, go-gateway, and then use it from both taipei-torrent and go-nat-pmp? It is stand-alone functionality, and that way potentially other packages can use it as well.

**Comment by chmduquesne** [comment]
+1

I would even contribute an improvement for this function for Linux.

**Comment by chmduquesne** [comment]
But why name it "go-gateway"? Just "gateway" would be simpler IMHO.

**Comment by jackpal** [comment]
Good point, will rename.

**Comment by jackpal** [comment]
Added NewClientForDefaultGateway. Made it a separate function because it returns an error code.
